---
name: HTTP-MobileAgent-Plugin-CIDR
version: 0.0.1
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: Add IP address check method to HTTP::MobileAgent
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  HTTP::MobileAgent::Plugin::CIDR:
    file: lib/HTTP/MobileAgent/Plugin/CIDR.pm
    version: 0.0.1
  HTTP::MobileAgent::Plugin::CIDR::RegEx:
    file: lib/HTTP/MobileAgent/Plugin/CIDR/RegEx.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
